# Для автоматической проверки ERB шаблонов
require:
  - rubocop-erb

# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Добавил для втоматической проверки и добавления пустой строки в конце файлов
Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline

# Использовать однострочный формат (def method; end)
Style/EmptyMethod:
  EnforcedStyle: compact
