services:
  - type: web
    name: the-guru-project
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: the-guru-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true

  - type: postgresql
    name: the-guru-db
    ipAllowList: []
    plan: free
    version: 15 