service: the-guru-project
image: yurik7/kamal2-test
servers:
  - 91.222.239.113
registry:
  username: yurik7
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
env:
  secret:
    - RAILS_MASTER_KEY
    - DOCKER_HUB_TOKEN
    - KAMAL_REGISTRY_PASSWORD